import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'

import styles from '@/styles/Home.module.css'
import menuStyles from '@/styles/menuStyles.module.css'

// custom components

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
    <>
      <Head>
        <title>Shameless Self Promotion!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      <p>
        Go to my business Card if you want to get in touch with me! <Link href='BusinessCard/businessCard'>Profile</Link>
      </p>
      <p>Here are some CSS-Animations i created, recreated and modified <Link href="CssAnimation/cssanimation">Animations</Link></p>
      <p> REACT-HOOK-FORM <Link href="Showcase/react_hook_form">HERE</Link></p>
{/* 
        <div className={menuStyles.menu}>
          <div className={menuStyles.menu_items}>
            <a className={menuStyles.menu_item0} >Click HERE!</a>
            <a className={menuStyles.menu_item1} >Click HERE!</a>
            <a className={menuStyles.menu_item2} >Click HERE!</a>
            <a className={menuStyles.menu_item3} >Click HERE!</a>
          </div>
            <div className={menuStyles.menu_background_pattern}>
          </div>
        </div>
 */} 
        <p>
        Go to my first blog entry<Link href='posts/first_post'>here</Link>
        </p>
      </main>
    </>
  )
}
